import ProfilePic from "../../images/profilePicture.png";
const data = {
  requests: [
    {
      id: 1,
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      image: ProfilePic,
      dob: "20-10-1999",
      phoneNumber: "0999999999",
      certificationNumber: "Marketing Strategy",
      institutionId: "1001",
      graduationYear: "2015",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
    {
      id: 2,
      name: "Jogn Summers",
      email: "JohnSingla@gmail.com",
      dob: "20-10-1998",
      image: ProfilePic,
      phoneNumber: "0999900999",
      certificationNumber: "Marketing Strategy",
      institutionId: "1003",
      graduationYear: "2018",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
    {
      id: 3,
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      dob: "20-10-2009",
      image: ProfilePic,
      phoneNumber: "09999999898",
      certificationNumber: "Marketing Strategy",
      institutionId: "1009",
      graduationYear: "2015",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
    {
      id: 4,
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      dob: "20-10-2000",
      image: ProfilePic,
      phoneNumber: "09999997777",
      certificationNumber: "Marketing Strategy",
      institutionId: "10012",
      graduationYear: "2015",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
    {
      id: 5,
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      dob: "20-10-2002",
      image: ProfilePic,
      phoneNumber: "099956569999",
      certificationNumber: "Marketing Strategy",
      institutionId: "10014",
      graduationYear: "2015",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
    {
      id: 6,
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      dob: "20-10-2005",
      image: ProfilePic,
      phoneNumber: "099999909089",
      certificationNumber: "Marketing Strategy",
      institutionId: "10078",
      graduationYear: "2015",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
    {
      id: 7,
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      dob: "20-10-1999",
      image: ProfilePic,
      phoneNumber: "0999999999",
      certificationNumber: "Marketing Strategy",
      institutionId: "1001",
      graduationYear: "2015",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
    {
      id: 8,
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      dob: "20-10-1999",
      image: ProfilePic,
      phoneNumber: "0999999999",
      certificationNumber: "Marketing Strategy",
      institutionId: "1001",
      graduationYear: "2015",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
    {
      id: 9,
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      dob: "20-10-1999",
      image: ProfilePic,
      phoneNumber: "0999999999",
      certificationNumber: "Marketing Strategy",
      institutionId: "1001",
      graduationYear: "2015",
      message:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    },
  ],
  applicants: [
    {
      id: 1,
      expirationDate: "23-03-2022",
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      image: ProfilePic,
      issueDate: "2002-02",
      certification: "Public Relation Manager",
      corpType: "Big corp",
      corpName: "San Francisco, USA",
      score: "100%",
      verifiedBy: "Ander Thompson",
      verificationPersonPosition:
        "Assistant Director of Human Resource By Big Corp",
    },
    {
      id: 2,
      expirationDate: "23-03-2022",
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      image: ProfilePic,
      issueDate: "2002-02",
      certification: "Public Relation Manager",
      corpType: "Big corp",
      corpName: "San Francisco, USA",
      score: "100%",
      verifiedBy: "Ander Thompson",
      verificationPersonPosition:
        "Assistant Director of Human Resource By Big Corp",
    },
    {
      id: 3,
      expirationDate: "23-03-2022",
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      image: ProfilePic,
      issueDate: "2002-02",
      certification: "Public Relation Manager",
      corpType: "Big corp",
      corpName: "San Francisco, USA",
      score: "100%",
      verifiedBy: "Ander Thompson",
      verificationPersonPosition:
        "Assistant Director of Human Resource By Big Corp",
    },
    {
      id: 4,
      expirationDate: "23-03-2022",
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      image: ProfilePic,
      issueDate: "2002-02",
      certification: "Public Relation Manager",
      corpType: "Big corp",
      corpName: "San Francisco, USA",
      score: "100%",
      verifiedBy: "Ander Thompson",
      verificationPersonPosition:
        "Assistant Director of Human Resource By Big Corp",
    },
    {
      id: 5,
      expirationDate: "23-03-2022",
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      image: ProfilePic,
      issueDate: "2002-02",
      certification: "Public Relation Manager",
      corpType: "Big corp",
      corpName: "San Francisco, USA",
      score: "100%",
      verifiedBy: "Ander Thompson",
      verificationPersonPosition:
        "Assistant Director of Human Resource By Big Corp",
    },
    {
      id: 6,
      expirationDate: "23-03-2022",
      name: "Mark Summers",
      email: "MarkSummers@gmail.com",
      image: ProfilePic,
      issueDate: "2002-02",
      certification: "Public Relation Manager",
      corpType: "Big corp",
      corpName: "San Francisco, USA",
      score: "100%",
      verifiedBy: "Ander Thompson",
      verificationPersonPosition:
        "Assistant Director of Human Resource By Big Corp",
    },
  ],
  settings: {
    apiKey: "31d6cfe0d16ae931b73c59d7e0c08567hjdetufg9c0",
    apiSecret: "31d6cfe0d16ae931b73c59d7e0c08567hjdetufg9c0",
  },
};

export default data;
